from __future__ import annotations

from typing import Protocol

from app.models import Currency


class Broker(Protocol):
    """Common boundary between strategies and an execution venue."""

    async def restore(self) -> None: ...
    async def get_accounts(self) -> list[dict]: ...
    async def get_positions(self) -> list[dict]: ...
    async def get_buying_power(self, currency: Currency = Currency.KRW) -> dict: ...
    async def get_sellable_quantity(self, symbol: str) -> dict: ...
    async def list_orders(self, status: str | None = None) -> list[dict]: ...
    async def get_order(self, order_id: str) -> dict: ...
    async def place_order(self, request: dict) -> dict: ...
    async def cancel_order(self, order_id: str) -> dict: ...
    async def reconcile(self) -> dict: ...
